### ISSUE TITLE
Can't find piecewiselinear? 

### ISSUE THREAD

**Issue by 1ozturkbe** [1ozturkbe/soromotoropt#1]
@chriscoey I was wondering if you could help me out with something quick. I almost have the model going in a notebook in the latest commit (in convexBurnPLO.ipynb) but unfortunately I am getting an error with piecewiselinear that I cannot figure out:
```julia
MethodError: no method matching piecewiselinear(::JuMP.Model, ::Array{JuMP.Variable,2}, ::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}, ::Array{Float64,1})
Closest candidates are:
  piecewiselinear(::JuMP.Model, ::Union{JuMP.GenericAffExpr{Float64,JuMP.Variable}, JuMP.Variable}, ::Any, ::Any; method) at C:\Users\Berk\.julia\v0.6\PiecewiseLinearOpt\src\jump.jl:24
  piecewiselinear(::JuMP.Model, ::Union{JuMP.GenericAffExpr{Float64,JuMP.Variable}, JuMP.Variable}, ::Any, ::Function; method) at C:\Users\Berk\.julia\v0.6\PiecewiseLinearOpt\src\jump.jl:19
  piecewiselinear(::JuMP.Model, ::JuMP.Variable, ::Union{JuMP.GenericAffExpr{Float64,JuMP.Variable}, JuMP.Variable}, ::Any, ::Any, ::Function; method) at C:\Users\Berk\.julia\v0.6\PiecewiseLinearOpt\src\jump.jl:516
  ...
```
Really frustrating... checked my installation of PiecewiseLinearOpt a few times and seems like there shouldn't be any issues. Would you mind running this on your machine to see if it is specific to mine?

**Comment by chriscoey** [comment]
It is installed fine, otherwise you wouldn't get this error message. It looks as if you are trying to call piecewiselinear on a matrix of JuMP variables (second argument), which you can't do. The message is telling you the second argument must be a JuMP variable or a scalar affine expression (like 2x+y+1).

**Comment by chriscoey** [comment]
I looked at the code and this is indeed what you're doing. You should instead do a loop over i in 1:nctrl and j in 1:nt and do something like 
`logabsx[i,j] = piecewiselinear(m, absx[i,j], 0:rn:r, log.(0:rn:r))`

**Comment by 1ozturkbe** [comment]
Oy right, I always forget that it's slightly harder to make vectorized constraints in Julia.

**Comment by 1ozturkbe** [comment]
Lol, I also called log(0).

**Comment by 1ozturkbe** [comment]
Sorry about the trivial issue. I guess I have been banging my head on this hard today and gave myself a metaphorical concussion. Now I'm breaking other things. Closing.

**Comment by chriscoey** [comment]
i went through the same learning process at one stage, no question is dumb and I'm happy to help!
